bug:Missing command
vmware/powershell-module-for-vmware-cloud-foundation-power-management pull request #102
Opened 2024-04-04 12:35 UTC by burnsjared0415

### Summary
Command `$cluster = Get-VCFCluster | Where-Object { $_.id -eq ($workloadDomain.clusters.id) }` was removed on accident, also updated a couple variables

### Type

- [x] Bugfix
- [ ] Enhancement or Feature
- [ ] Code Style or Formatting
- [ ] Documentation
- [ ] Refactoring
- [ ] Chore
- [ ] Other
        Please describe:

### Breaking Changes?

- [x] Yes, there are breaking changes.
- [ ] No, there are no breaking changes.

### Test and Documentation

- [x] Tests have been completed.
- [ ] Documentation has been added or updated.

### Issue References
Closes #101 

### Additional Information

2024-04-04 13:19 UTC, tenthirtyam requested changes

2024-04-04 13:19 UTC, tenthirtyam commented on SampleScripts/PowerManagement-ManagementDomain.ps1
> +            $nsxmgrPass = (Get-VCFCredential | Where-Object ({ $_.resource.resourceName -eq $nsxtMgrfqdn -and $_.credentialType -eq "API" })).password
```suggestion
            $nsxMgrPass = (Get-VCFCredential | Where-Object ({ $_.resource.resourceName -eq $nsxtMgrfqdn -and $_.credentialType -eq "API" })).password
```

2024-04-04 13:19 UTC, tenthirtyam commented on SampleScripts/PowerManagement-ManagementDomain.ps1
> +            if ($nsxmgrPass) {
```suggestion
            if ($nsxMgrPass) {
```

2024-04-04 13:19 UTC, tenthirtyam commented on SampleScripts/PowerManagement-ManagementDomain.ps1
> +                $Pass_encrypted = $nsxmgrPass | ConvertTo-SecureString -AsPlainText -Force | ConvertFrom-SecureString
```suggestion
                $nsxMgrPassEncrypted = $nsxMgrPass | ConvertTo-SecureString -AsPlainText -Force | ConvertFrom-SecureString
```

2024-04-04 13:19 UTC, tenthirtyam commented on SampleScripts/PowerManagement-ManagementDomain.ps1
>                  $Pass_encrypted = $null
$nsxMgrPassEncrypted

2024-04-04 13:19 UTC, tenthirtyam commented on SampleScripts/PowerManagement-ManagementDomain.ps1
> +                        $clustername_extra = $Clusterid.name
Was there a variable conflict?

2024-04-15 21:24 UTC, garlicNova reviewed
There seemed to be validation issue with this section.  by changing $clustername to $clustername_extra functional breaks for prior cmdlet calls at line 205, 228, 250, 251, 257, 267 and 330.

2024-04-15 21:24 UTC, garlicNova commented on SampleScripts/PowerManagement-ManagementDomain.ps1
>                                  Write-PowerManagementLogMessage -Type WARNING "Cancelling shutdown of $clustername. Exiting..."
```suggestion
                                Write-PowerManagementLogMessage -Type WARNING "Cancelling shutdown of $clustername_extra. Exiting..."
```

2024-04-15 21:24 UTC, garlicNova commented on SampleScripts/PowerManagement-ManagementDomain.ps1
>                                          Set-DrsAutomationLevel -server $vcfVcenterDetails.fqdn -user $vcfVcenterDetails.ssoAdmin -pass $vcfVcenterDetails.ssoAdminPass -cluster $clustername -level Man
```suggestion
                                        Set-DrsAutomationLevel -server $vcfVcenterDetails.fqdn -user $vcfVcenterDetails.ssoAdmin -pass $vcfVcenterDetails.ssoAdminPass -cluster $clustername_extra -level Manual
```

2024-04-15 21:24 UTC, garlicNova commented on SampleScripts/PowerManagement-ManagementDomain.ps1
> +            $cluster = Get-VCFCluster | Where-Object { $_.id -eq ($workloadDomain.clusters.id) }
$cluster = Get-VCFCluster | Where-Object { $_.id -eq ($workloadDomain.clusters.id) }

should be within the else{} for when there's a single cluster exists in the management domain.

2024-04-15 21:31 UTC, garlicNova commented
I am unable to validate the commit due to other issues as well.  
line: 196 foreach ($clusterid in $mgmtClusterIds) when the cluster in which sfo-m01-vc01 vm exists is higher than other cluster in this list, the function will shutdown sfo-m01-vc01 vm before other clusters in the domain shutdown down.  
line 349: if i sort the cluster list to have the main cluster be the last one on the list, the script ends at line 349 and the startup json is not created, therefore i am unable to powerup the environment through the script.  
Please make the above changes and re-run the module E2E based on step 6 in https://vmware.github.io/powershell-module-for-vmware-cloud-foundation-power-management/documentation/#usage-examples

2024-05-02 18:10 UTC, garlicNova commented
> line: 196 foreach ($clusterid in $mgmtClusterIds) when the cluster in which sfo-m01-vc01 vm exists is higher than other cluster in this list, the function will shutdown sfo-m01-vc01 vm before other clusters in the domain shutdown down. i am not sure understand this comment. I am really not sure what the issues are, i can't replicate these issues

ah i found the issue, line 199

2024-05-02 18:11 UTC, garlicNova commented on SampleScripts/PowerManagement-ManagementDomain.ps1
>                          if (!$isDefault) {
```suggestion
                        if (!$clusterid.isDefault) {
```

2024-07-16 19:24 UTC, tenthirtyam commented
Merging this one after discussions with @joisika. He will review the current state and initiate some in-depth testing for the next release.

2024-07-16 19:25 UTC, merged